language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - which pecl && echo yes | pecl install pecl_http || true
  - travis_retry composer install --prefer-source --no-interaction
  - npm install

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpunit --coverage-text --coverage-clover=coverage.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then phpunit; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
