language: php

sudo: false

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction
  - npm install

script: vendor/bin/phpunit ${PHPUNIT_FLAGS}
