language: php
php:
  - 5.3
  - 5.4

before_script:
  - sudo aptitude -y install subversion
  - npm install git://github.com/baalexander/node-xmlrpc.git
  - ./vendor.sh

script:
  - phpunit

notifications:
  email:
    - lstrojny@php.net
