language: php
php:
  - 5.3
  - 5.4
  - 5.5

env:
    - ZF2_VERSION=2.0.1   ZF1_VERSION="1.10.*"   GUZZLE_VERSION="2.7.*"    MONOLOG_VERSION="1.0.*"     BUZZ_VERSION=0.5         HTTP_VERSION=pecl_http-1.6.6
    - ZF2_VERSION=2.0.2   ZF1_VERSION="1.11.*"   GUZZLE_VERSION="2.8.*"    MONOLOG_VERSION="1.1.*"     BUZZ_VERSION=0.6         HTTP_VERSION=pecl_http-1.6.6
    - ZF2_VERSION=2.0.3   ZF1_VERSION="1.12.*"   GUZZLE_VERSION="3.0.*"    MONOLOG_VERSION="1.2.*"     BUZZ_VERSION=0.7         HTTP_VERSION=pecl_http-1.7.4
    - ZF2_VERSION="2.0.*" ZF1_VERSION=dev-trunk  GUZZLE_VERSION=dev-master MONOLOG_VERSION=dev-master  BUZZ_VERSION=dev-master  HTTP_VERSION=pecl_http-1.7.4

before_script:
  - sudo aptitude install -y libcurl-dev
  - echo yes | sudo pecl install ${HTTP_VERSION}
  - wget http://getcomposer.org/composer.phar
  - php composer.phar require zendframework/zend-http:${ZF2_VERSION} zendframework/zendframework1:${ZF1_VERSION} guzzle/guzzle:${GUZZLE_VERSION} monolog/monolog:${MONOLOG_VERSION} kriswallsmith/buzz:${BUZZ_VERSION}
  - php composer.phar install --dev
  - npm install git://github.com/baalexander/node-xmlrpc.git

notifications:
  email:
    - lstrojny@php.net
