language: php
php:
  - 5.3
  - 5.4

before_script:
  - echo yes | pecl install ${HTTP_VERSION}
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - npm install git://github.com/baalexander/node-xmlrpc.git

script: phpunit --exclude-group java --exclude-group python

notifications:
  email:
    - lstrojny@php.net
